# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'


target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
	pod 'PSPDFKit', podspec:'https://my.pspdfkit.com/pspdfkit-ios/latest.podspec'
	pod 'Instant', podspec: 'https://my.pspdfkit.com/instant/latest.podspec'

  end

end
